name: Build NordVPN Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: mm404/nordvpn-sidecar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Detect build version
      id: detect_version
      run: echo "VERSION=$(grep "^ARG NORDVPN_VERSION" Dockerfile | cut -d'=' -f2)" >> $GITHUB_ENV
    - name: Determine image tags
      id: determine_tags
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if [ -n "$PR_NUMBER" ]; then
          echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
          echo "${IMAGE_NAME}:pr-${PR_NUMBER}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
          echo "${IMAGE_NAME}:latest" >> $GITHUB_ENV
          echo "${IMAGE_NAME}:${VERSION}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: mm404
        password: ${{ secrets.DOCKER_HUB_KEY }}
    - name: Build multi-arch and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE_TAGS }}
        build-args: |
          GIT_REVISION=${{ github.sha }}
